FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --omit=dev # --only=production

# Copy application code
COPY . .

# Expose port
# EXPOSE 3000

# Health check
# HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
#    CMD node healthcheck.js || exit 1

# Start the application
CMD ["node", "index.js"]
